### PR TITLE
Wrote notebook featured in FITS video

### PR DESCRIPTION
**Pull request by ojustino**
I filled in the placeholder file. Perhaps we can also link to it in the description?

### CODE REVIEW

**Comment by ojustino** [comment]
I made the edits we discussed earlier this week to include the image/layer control widgets and show how to upload a file from its local path.

**All that's left is to add the link for the YT video once it's been uploaded.**

**Comment by ojustino** [comment]
As a side note, I get these warnings in the notebook both locally and on Binder. Is there anything we can do about them?

Importing `astroquery.SkyView` causes this: 

```
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0,
use the six module directly if it is still needed [astropy.extern.six]
```

`celestial.py:26` in `repoject` causes this: 

```
FutureWarning: Conversion of the second argument of issubdtype
from `float` to `np.floating` is deprecated. In future, it will be treated
as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(array.dtype, np.float):
```

**Comment by pkgw** [comment]
@ojustino The most recent release of astroquery, which just came out the other day, fixes the first warning, so that's something

**Comment by pkgw** [comment]
Looking good! Being able to load up the Swift image and blend between it and 2MASS is really nice.

**Pull request merged**
